IndexCoop/index-app

- package.json
- src/hooks/issuance/useIssuance.ts
- src/hooks/useTrade.ts
- src/hooks/useTradeFlashMintLeveraged.ts
- src/hooks/useTradeFlashMintZeroEx.ts
- src/utils/api/analytics.ts
- yarn.lock
Upgrade the arcxmoney analytics lib to 1.0.0.
&nbsp;
> Upgrade arcx

- src/hooks/useTrade.ts
- src/utils/api/analytics.ts
- src/utils/api/sentry.ts
Updates arcx tracking to make sure that all values are not `null`. Adds sentry capturing to be able to better check potential issues.
&nbsp;
> Update arcx tracking using sentry

- src/hooks/useTrade.ts
> Update log tx to only run when data is available

- package.json
- yarn.lock
> Update chakra and recharts

- src/components/page/Page.tsx
- src/utils/api/analytics.ts
Adds auto tracking pages for arcx.
&nbsp;
> Add auto tracking pages

- src/components/token-page/TokenPage.tsx
> Remove deprecation message for eth2xfli and eth2xbtc

- src/components/trade/_shared/DeprecatedTokenMessage.tsx
- src/components/trade/_shared/SelectTokenModal.tsx
- src/components/trade/flashmint/DirectIssuance.tsx
- src/components/trade/flashmint/index.tsx
- src/components/trade/swap/index.tsx
- src/utils/tokens.ts
* Enhances deprecation info for the user throughout the trade flow
* Fixes some issues
> Enhance deprecation info

- src/components/token-page/TokenPage.tsx
- src/utils/tokens.ts
> Fix eth/btc 2x fli not working in swap

- src/components/token-page/TokenPage.tsx
- src/components/trade/_shared/SelectTokenModal.tsx
- src/components/trade/flashmint/index.tsx
- src/components/trade/swap/index.tsx
- src/constants/tokens.ts
- src/utils/tokens.ts
Adds deprecated indices list. (Why make things easy when you can make it difficult)
&nbsp;
> Fix some tokens displaying wrong deprecated status

- src/components/trade/flashmint/index.tsx
> Update slippage for flash mints

- package.json
- src/constants/server.ts
- src/utils/api/zeroExUtils.ts
- src/utils/zeroExApi.ts
- yarn.lock
Fix typo in 0x affiliate address parameter
> Fix affiliate address

- src/hooks/issuance/useIssuanceQuote.ts
- src/hooks/useBestQuote/index.ts
* Hides savings message for 2xFLI's on Polygon - as they won't work with FlashMint any longer.
* Fixes type of boolean
> Update savings message

- package.json
- yarn.lock
> Remove wrongly added lib

- package.json
- public/index.html
- src/components/page/Footer.tsx
- src/components/page/header/NavContent.tsx
- src/components/page/header/Navigation.tsx
- src/components/trade/index.tsx
- src/index.tsx
- src/views/Homepage/index.tsx
- yarn.lock
* Removes navigation to show trade component only
* Upgrades flash-mint-sdk to fix issues with DATA-USDC quotes
* Update meta data to reflect that this is legacy products app
> Update legacy products

- package.json
- yarn.lock
* Fixes some potential issues when fetching quotes for indices that only have a single component
> Upgrade flash-mint-sdk

- package.json
- src/constants/tokens.ts
- src/hooks/useTradeFlashMintZeroEx.ts
- src/utils/flashMint/flashMintZeroExTransaction.ts
- src/utils/flashMint/quotes.ts
- src/utils/flashMintNotional/fmNotionalTransaction.test.ts
- yarn.lock
* Adds updated FlashMintSDK version 1.3.0
* Adds wsETH2
* Adds sETH2
* Minor clean up in tokens
&nbsp;
> Add wseth2

- package.json
- src/constants/tokens.ts
- src/hooks/useTradeFlashMintLeveraged.ts
- src/utils/flashMint/flashMintLeveragedTransaction.ts
- src/utils/flashMint/quotes.ts
- yarn.lock
* Upgrades FlashMintSDK
* Reenables BTC2xFLI and ETH2xFLI for FlashMint on mainnet
> Add BTC2xFLI for mainnet

- src/constants/tokens.ts
* Adds sETH2 to currencies list
> Fix sETH2 balance not showing

- src/providers/Balances/BalancesProvider.ts
- src/providers/Balances/index.tsx
> Fix balances

- src/utils/tokens.test.ts
- src/utils/tokens.ts
* Fixes leveraged token utility function (returning wrong values before)
&nbsp;
> Fix allocation charts

- src/views/productpages/DSETH.tsx
* Remove temporary fix for dseth apy - now that the APY format is the same for icETH and dsETH on the dune dashboard.
&nbsp;
> Fix dsETH APY

- src/constants/slippage.ts
> Update slippage for iceth

- .github/workflows/unit-tests.yml
> Update checkout to v3

- src/constants/tokens.ts
> Update dseth from geofencing

- src/components/page/Footer.tsx
> Fix logo dimensions in footer

- package.json
- yarn.lock
> Upgrade flash mint sdk to 1.6.0

- vercel.json
* Adds content security policy for the site (mainly defaults, only one exception for safe to be able to frame the site)
> Add content security policy

- package.json
- src/components/token-page/TokenComponentsTable.tsx
- src/components/token-page/TokenPage.tsx
- src/constants/tokens.ts
- src/hooks/useTokenComponents.ts
- src/utils/gasEstimatooor.test.ts
- src/utils/gasEstimatooor.ts
- yarn.lock
* Adds icSMMT back to production list
* Adds banner to inform about large purchases only
* Adds fetching NAV
* Updates FlashMintSDK to use new contracts
> icSMMT launch

- src/providers/Balances/BalancesProvider.test.ts
* Adds some simple tests for `BalancesProvider`
> Add tests for balances provider

- src/constants/tokens.ts
- src/providers/MarketData/index.tsx
* Removes GMI throwing market data issues - as it's delisted on coingecko
> Remove GMI

- src/app/bed/page.tsx
- src/app/btcfli/page.tsx
- src/app/dpi/page.tsx
- src/app/dseth/page.tsx
- src/app/ethfli/page.tsx
- src/app/gtceth/page.tsx
- src/app/iceth/page.tsx
- src/app/icsmmt/page.tsx
- src/app/mvi/page.tsx
- src/components/trade/_shared/QuickTradeSelector.tsx
- src/components/trade/swap/index.tsx
* Adds redirects for former products' path
* Some minor styling changes
> Add redirects

- src/lib/styles/theme.ts
> temp set fix light theme

- public/googleb87fb57ef01c44ff.html
> Add google verfication

- next.config.js
> task: add rewrites for previous paths

- src/constants/tokens.ts
> release ic21

- package-lock.json
- package.json
- src/constants/slippage.ts
- src/lib/hooks/useBestQuote/index.ts
* Removes RFQ only for ic21 to pick up UniV3 quotes as well
* Updates FlashMintSDK to latest version (2.2.2)
&nbsp;
> Remove RFQ only for ic21

- src/constants/slippage.ts
- src/lib/utils/slippage.test.ts
- src/lib/utils/slippage.ts
* Updates default slippage to 0.5%
> Update default slippage

- src/app/swap/[[...path]]/pathResolver.test.ts
- src/app/swap/[[...path]]/pathResolver.ts
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/hooks/useTradeTokenLists.test.ts
- src/lib/hooks/useTradeTokenLists.ts
- src/lib/providers/Balances/index.tsx
- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
* Updates path resolver class to always return tokens (for wrong paths, a default will be returned)
&nbsp;
> feat: resolve tokens from path

- next.config.js
- src/app/globals.css
- src/app/vaults/layout.tsx
- src/app/vaults/page.tsx
- src/app/vaults/providers.tsx
- src/app/vaults/types.ts
- src/app/vaults/vault-token-card.tsx
- src/components/page/header/HeaderV2.tsx
- src/components/page/header/LogoV2.tsx
- src/lib/hooks/useLedgerStatus.ts
Adds the `/vaults` page for icTBILL / icREAL
> feat: Vaults

- src/components/trade/swap/trade-details/index.tsx
> fix trade details header padding

- next.config.js
- src/lib/hooks/useApproval.ts
Adds redirects for `/ic21` and `/cdeti`.
> feat: ic21/cdeti redirects

- src/app/layout.tsx
> update safary script

- src/app/layout.tsx
> remove safary

- package-lock.json
- package.json
- src/app/swap/[[...path]]/page.tsx
- src/components/header/connect.tsx
- src/lib/utils/wagmi.ts
Update `wagmi` to remove connect-kit-loader (https://github.com/wevm/wagmi/releases/tag/wagmi%401.4.12) and remove deprecated/unused ledger live dep. 
&nbsp;
> chore: Remove ledger connect code

- src/components/trade/swap/index.tsx
Update `onClickTradeButton` when relevant inputs change.
&nbsp;
> fix: Update button callback values

- package-lock.json
- package.json
- src/components/settings/index.tsx
- src/components/skeleton/index.tsx
- src/components/swap/components/trade-details/index.tsx
- src/components/swap/components/trade-details/tag-flashmint.tsx
- src/components/swap/components/trade-details/tag.tsx
- src/components/swap/components/trade-details/trade-info.tsx
- src/components/swap/components/trade-input-selector.tsx
- src/components/swap/components/transaction-review/index.tsx
- src/components/swap/components/transaction-review/types.ts
- src/components/swap/hooks/use-swap/index.tsx
- src/components/swap/hooks/use-swap/trade-details-builder.ts
- src/components/swap/hooks/use-transaction-review-modal.tsx
- src/components/swap/index.tsx
- src/components/toggle/index.tsx
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
* Adds a toggle for switching different quote types (swap|flashmint) - if available
* Shows 0x quote as soon as available, loads flash mint quote in the background
* Fixes localization issues of output amount
* Uses diff to use less runs when calculating a flash mint quote (isMinting: true) to fit the user's input amount
> feat: add flashmint toggle

- src/components/swap/index.tsx
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/should-return-quote.test.ts
- src/lib/hooks/use-best-quote/utils/should-return-quote.ts
- src/lib/utils/api/analytics.ts
* Removes label for input token amount in USD (to avoid confusion around selected FlashMint quotes)
* Enhances FlashMint quoting mechanism
> task: improve flashmint quotes

- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/utils/gas-defaults.ts
* A first simple solution for getting more realistic gas prices for tx's - especially, if the user doesn't have the necessary funds.
> feat: add gas table

- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/index-token-amount.test.ts
> add determining factor based on diff being negative/positive

- src/lib/hooks/use-best-quote/utils/flashmint.ts
> remove duplicate gas estimate call

- src/lib/utils/simulator.ts
* Add logging tenderly links to console
* https://blog.tenderly.co/changelog/public-sharing-of-transactions-devnets-forks-and-simulations/
> feat: log tendery links to console

- src/constants/contracts.ts
- src/lib/hooks/use-best-quote/utils/issuance/index.ts
- src/lib/hooks/use-best-quote/utils/issuance/redemption.ts
* Adds some more values to the quote
> feat: add redemption quotes (part 2)

- src/constants/contracts.ts
- src/lib/hooks/use-best-quote/types.ts
- src/lib/hooks/use-best-quote/utils/issuance/debt-issuance-module-v2-abi.ts
- src/lib/hooks/use-best-quote/utils/issuance/index.ts
- src/lib/hooks/use-best-quote/utils/issuance/redemption.ts
> fea: add (empty) redemption quotes

- src/lib/hooks/use-approval.ts
* Fixes approvals fixing `isApproved` condition
> fix: approvals

- package-lock.json
- package.json
- src/app/swap/[[...path]]/page.tsx
- src/components/chart/components/date-range.tsx
- src/components/chart/components/line-chart.tsx
- src/components/chart/components/price.tsx
- src/components/chart/components/range-selection.tsx
- src/components/chart/index.tsx
- src/lib/styles/colors.tsx
* Adds chart component (no data integration and won't be displayed yet)
> feat: add chart component

- hardhat.config.js
- package.json
- src/lib/utils/wagmi.ts
> test: add support for localhost and funding accounts

- src/components/swap/index.tsx
- src/constants/tokens.ts
* Makes DPI, MVI, BED, dsETH available to everyone
* Reintroduces IP blocking on app level
* On Cloudflare the US IP blocking rule will be removed ℹ️ 
> chore: readd ip blocking in-app

- package-lock.json
- package.json
- src/app/leverage/layout.tsx
- src/app/leverage/page.tsx
- src/components/footer/footer-link.tsx
- src/components/footer/index.tsx
- src/components/footer/logo-full.tsx
- src/components/header/index.tsx
- src/components/header/link.tsx
- src/components/header/logo.tsx
- src/lib/styles/tailwind.config.ts
* Adds dark mode for leverage ui
* Updates tailwind to latest version
> feat: add dark mode

- src/components/external/safary-script.tsx
- src/components/header/index.tsx
> chore: update prod keys

- src/app/leverage/components/leverage-widget/components/buy-sell-selector.tsx
- src/app/leverage/components/leverage-widget/components/leverage-selector.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/layout.tsx
- src/app/leverage/page.tsx
- src/app/leverage/provider.tsx
- src/components/chart/components/price.tsx
- src/components/swap/components/caption.tsx
- src/components/swap/components/trade-input-selector.tsx
* Adds leverage trade widget
* Adds leverage provider
* Adds toggling for minting state
g the following to be true:_
> feat: add leverage widget

- package-lock.json
- package.json
- public/assets/chevron-stats-icon.svg
- src/app/leverage/components/leverage-chart/index.tsx
- src/app/leverage/components/stats.tsx
- src/app/leverage/page.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/types.ts
- src/app/leverage/use-formatted-data.tsx
> feat: integrate stats

- src/app/leverage/components/leverage-widget/components/leverage-selector.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/stats.tsx
- src/app/leverage/provider.tsx
- src/components/onramp/index.tsx
- src/components/swap/index.tsx
> feat: leverage ui

- src/app/leverage/components/leverage-widget/components/leverage-selector.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/stats.tsx
- src/app/leverage/provider.tsx
- src/components/onramp/index.tsx
- src/components/onramp/utils.ts
- src/components/swap/components/navigation.tsx
- src/components/swap/index.tsx
> feat: add onramp

- package-lock.json
- package.json
- src/app/swap/[[...path]]/page.tsx
- src/app/swap/layout.tsx
- src/components/swap/components/transaction-review/index.tsx
- src/components/swap/hooks/use-swap/index.tsx
- src/components/swap/hooks/use-trade-button-state.tsx
- src/components/swap/hooks/use-transaction-review-modal.tsx
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/hooks/use-approval.ts
- src/lib/hooks/use-best-quote/utils/issuance/index.ts
- src/lib/utils/gas-defaults.ts
- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
* Re-adds migration banners
* Re-adds new 2x tokens
> feat: add migration

- src/constants/contracts.ts
* Updates debt issuance module for FLI redemptions
> update debt issuance module

- src/app/pre-sale/components/popup/index.tsx
- src/app/pre-sale/components/pre-sale-widget/components/buy-sell-selector.tsx
- src/app/pre-sale/components/pre-sale-widget/index.tsx
- src/app/pre-sale/components/pre-sale-widget/styles.css
- src/app/pre-sale/layout.tsx
- src/app/pre-sale/page.tsx
* Adds empty pre-sale page (and layout)
* Adds pre-sale popup
* Adds pre-sale widget (copy/pasta for now from leverage widget, will be adapted in following PRs)
> feat: add pre sale widget

- src/app/leverage/provider.tsx
- src/app/pre-sale/components/pre-sale-widget/index.tsx
- src/app/pre-sale/components/pre-sale-widget/use-formatted-data.tsx
- src/app/pre-sale/providers/deposit-provider.tsx
- src/app/pre-sale/providers/presale-provider.tsx
- src/components/supply/use-reth-supply.ts
- src/lib/utils/index.ts
* Adds data for balances
* Adds presale provider
* Adds tvl data
> feat: add presale widget data

- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
> feat: add eth2x swapping

- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/best-quote.ts
> fix: best quote selection

- src/app/layout.tsx
- src/components/external/mava-script.tsx
> feat: Mava integration

- src/lib/utils/abi/interfaces.ts
* minor change: removes obsolete interface
> remove ethers ref

- src/lib/hooks/use-approval.ts
* Fixes the case where a user would reject signing the approval tx (which would result in an infinite spinner)
> fix: rejecting approvals

- src/app/presales/components/faq-section/index.tsx
- src/app/presales/components/more-questions/index.tsx
- src/app/presales/components/pre-sale-widget/index.tsx
- src/app/presales/constants.ts
> feat: launch hyeth presale

- src/app/presales/components/pre-sale-token-card/index.tsx
- src/app/presales/providers/presale-provider.tsx
- src/lib/utils/index.ts
* Fixes total deposits of wstETH in hyETH presale
* Introduces new util function `formatWei`
> fix: total deposits

- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/stats.tsx
- src/app/leverage/layout.tsx
- src/app/leverage/provider.tsx
- src/components/swap/components/transaction-review/components/bottom-message.tsx
- src/components/swap/components/transaction-review/components/contract-section.tsx
- src/components/swap/components/transaction-review/components/from-to.tsx
- src/components/swap/components/transaction-review/components/network-badge.tsx
- src/components/swap/components/transaction-review/components/simulation.tsx
- src/components/swap/components/transaction-review/index.tsx
- src/components/swap/components/transaction-review/styles.css
* Adds tx review for leverage UI introducing a dark mode (only used when explicitly set)
* For testing the modal opens up on the clicking the trade button right now (no real data)
> feat: tx review leverage

- src/app/presales/components/pre-sale-widget/use-rewards.tsx
- src/components/swap/index.tsx
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-best-quote/utils/issuance/issuance-quote.ts
- src/lib/hooks/use-best-quote/utils/issuance/redemption-quote.ts
- src/lib/hooks/use-trade.ts
* Removes obsolete logs down to 20 total - most of them will only show when logging error cases
> remove logs

- src/components/swap/index.tsx
> feat: Onramp CTA analytics

- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/use-formatted-data.tsx
* Adds some prep work for adding leverage quotes
> feat: prep for quote

- src/app/leverage/provider.tsx
> add fake quote for testing

- src/app/leverage/components/trading-view-widget.tsx
- src/app/leverage/page.tsx
Fallback in case the 💯 chart isn't ready.
> feat: Trading View chart

- src/app/leverage/components/leverage-widget/components/fees.tsx
- src/app/leverage/components/leverage-widget/index.tsx
* Adds fees component (w/ static test data for now)
* Updates button label to be `Review Transaction`
> add fees component

- package-lock.json
- package.json
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/app/presales/components/pre-sale-widget/index.tsx
- src/components/swap/hooks/use-trade-button-state.tsx
- src/components/swap/index.tsx
- src/constants/chains.ts
- src/constants/tokens.ts
- src/lib/hooks/use-network.ts
- src/lib/utils/wagmi.ts
* Adds Arbitrum chain
* Introduces handling around multi chain e.g. making sure that only desired chains are connected for the individual trade UI's
* Adds all new index tokens (and updates Arbitrum token addresses)
* Adds approvals code
* Updates FlashMintSDK (for new dsETH issuance)
> feat: add arbitrum

- src/lib/hooks/use-best-quote/index.ts
- src/lib/utils/gas-defaults.ts
> fix: Handle 0x quote error

- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
* Adds new endpoint for getting quotes
* Replaces `Swap` quotes from 0x with new endpoint for all index tokens - except ic21
* Hides banner (hiding for now in case we need to display again due to some issues in the next days)
> feat: add index swap quote

- src/app/swap/layout.tsx
- src/lib/hooks/use-best-quote/utils/index-quote.ts
> hide banner

- src/app/leverage/components/faq-section/index.tsx
- src/app/leverage/components/trading-view-widget.tsx
- src/app/leverage/page.tsx
- src/components/header/index.tsx
Updates chart styling and toggles chart displayed based on the base token.
> feat: Chart enhancements

- src/app/presales/components/pre-sale-section/index.tsx
- src/app/presales/components/pre-sale-token-card/index.tsx
- src/app/presales/components/pre-sale-token-card/status-chip.tsx
- src/app/presales/components/pre-sale-widget/index.tsx
- src/app/presales/constants.ts
- src/app/presales/types.ts
Adds support for presale close (target met).
> feat: Presale close

- src/components/swap/components/trade-details/index.tsx
* Adds LI.FI label to quote preview
> add lifi label

- src/app/products/components/product-list.tsx
- src/app/products/layout.tsx
Fixes corners on scroll-enabled systems.
> fix: Products scrollbar

- package-lock.json
- package.json
- src/app/leverage/components/leverage-widget/components/fees.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/constants/tokens.ts
- src/lib/hooks/use-wallet.ts
- src/lib/utils/fetch-cost-of-carry.ts
Adds cost of carry to fees on the leverage widget.
> feat: Leverage cost of carry

- package-lock.json
- package.json
- src/app/leverage/components/leverage-widget/components/receive.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/use-formatted-data.tsx
- src/components/swap/components/transaction-review/components/submission-result.tsx
- src/constants/tokens.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-token-price.ts
- src/lib/hooks/use-wallet.ts
- src/lib/utils/api/coingecko.ts
- src/lib/utils/api/nav.ts
- src/lib/utils/api/zeroex-utils.ts
- src/lib/utils/tokens.ts
* Adds remaining changes to make quotes for the new leveraged tokens on Arbitrum work
> feat: add leverage quotes

- src/app/presales/components/pre-sale-section/index.tsx
- src/app/presales/components/pre-sale-token-card/index.tsx
- src/app/presales/components/pre-sale-token-card/status-chip.tsx
- src/app/presales/constants.ts
- src/app/presales/providers/presale-provider.tsx
- src/app/presales/types.ts
> feat: Presale enhancements

- src/app/leverage/components/leverage-widget/components/fees.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/components/trade-button/index.tsx
- src/lib/utils/fetch-cost-of-carry.ts
- Fixes cost of carry calculation
- Updates fees copy
- Changes trade button spinner color so it's visible on dark screens
- Sign terms warning
> fix: Leverage feedback

- package-lock.json
- package.json
- src/app/leverage/use-formatted-data.tsx
- src/constants/chains.ts
- src/lib/hooks/use-approval.ts
- src/lib/utils/block-explorer.ts
* Updates approvals to work on Arbitrum (or with any available token address for the current selected network)
* Adds the correct block explorer url for Arbitrum
* Updates gas fees formatting 
* Updates a few dependencies
* Successfully tested approvals and buying again on Arbitrum (redeeming is currently blocked by the contract bug) ✅ 
> update leverage UI

- src/lib/hooks/use-best-quote/utils/index-quote.ts
* Updates the quote provider for the Index API to the new response format which will be introduced with https://github.com/IndexCoop/cloudflare-workers/pull/136
> update index api

- src/app/leverage/components/faq-section/index.tsx
Adds the FAQs for the new leverage widget.
> feat: Leverage FAQ

- src/lib/hooks/use-analytics.ts
Adds `walletAddress` for referral distribution hooks.
> chore: Add wallet address analytics

- package-lock.json
- package.json
Update tokenlists for new leverage tokens.
> chore: Update leverage tokens

- package-lock.json
- package.json
* Updates FlashMintSDK w/ all necessary changes for the leveraged tokens on Arbitrum
> update flash mint sdk

- src/lib/hooks/use-trade.ts
* Fixes `getInputTokenBalance` (not taking chainId into account)
> fix: get input token balance

- src/lib/providers/sign-terms-provider/index.tsx
Ensure the signature state is reset on address change.
> fix: Reset signature state

- src/app/leverage/components/faq-section/index.tsx
> chore: Leverage FAQ updates

- src/components/swap/index.tsx
Ensures the warning is displayed if not tradable.
> fix: Tradable pair state

- src/app/leverage/components/your-tokens.tsx
- src/app/leverage/constants.ts
- src/app/leverage/page.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/components/swap/components/select-token-modal.tsx
- src/lib/hooks/use-balance.ts
Refetch token balances on calls to `reset`
> feat: Refetch token balances

- src/app/leverage/page.tsx
> fix: Pin chart width

- src/feature-flags.ts
> enable lev suite

- src/app/leverage/components/faq-section/index.tsx
- src/app/leverage/page.tsx
- src/app/leverage/types.ts
- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/constants/tokens.ts
> fix: leverage suite UI

- src/app/leverage/components/leverage-widget/components/fees.tsx
- src/components/banners/leverage-banner.tsx
Fixes bps copy and adds tooltips.
> chore: Leverage UX enhancements

- src/app/leverage/components/leverage-widget/index.tsx
- src/components/swap/components/select-token-modal.tsx
- src/lib/hooks/use-balance.ts
Use correct chain when fetching balances and avoid empty balance call.
> fix: Empty balance call

- src/lib/providers/sign-terms-provider/index.tsx
- tsconfig.json
> fix: Remove unreachable return

- package-lock.json
- package.json
- src/app/leverage/provider.tsx
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-best-quote/utils/index-token-amount.ts
- src/lib/hooks/use-token-price.ts
- src/lib/hooks/use-wallet.ts
- src/lib/utils/api/zeroex.ts
- src/lib/utils/tokens.ts
* Adds flash minting for hyETH in trade flow
> feat: add hyeth flashmint

- src/app/products/components/product-list.tsx
> fix: Hide empty price change

- package-lock.json
- package.json
* Updates FlashMintSDK to fix issue with redeeming hyETH to ERC-20s
> build: upgrade flash mint sdk

- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
* Adds GUSD to all possible pairs as currency (wherever not available yet)
> feat: add gusd where missing and possible

- package-lock.json
- package.json
* Update FlashMintSDK to patch hyETH quotes
> build: update flash mint sdk

- package-lock.json
- package.json
- src/app/prt-staking/components/faq-section/index.tsx
- src/app/prt-staking/components/prt-section/prt-card.tsx
- src/app/prt-staking/components/prt-section/prt-widget.tsx
- src/app/prt-staking/constants.ts
- src/app/prt-staking/provider.tsx
- src/components/header/index.tsx
- src/feature-flags.ts
- src/lib/hooks/use-approval.ts
- **Add audit link**
- **Add distribution diff**
- **Update signing flow**
> feat: Staking enhancements

- src/app/products/components/product-list.tsx
- src/app/products/constants/tokens.ts
- src/app/prt-staking/components/prt-section/prt-card.tsx
- **Remove extraneous period**
- **Reorder products**
- **Add 0 apy handling**
> chore: App UX tweaks

- src/components/banners/leverage-banner.tsx
- src/lib/hooks/use-best-quote/index.ts
* Temp disable swap due to Li.Fi exploit
> temp disable swap

- src/app/presales/components/popup/index.tsx
- src/app/presales/components/pre-sale-token-card/index.tsx
- src/app/presales/components/pre-sale-widget/components/deposit-withdraw-selector.tsx
- src/app/presales/components/pre-sale-widget/index.tsx
- src/app/presales/constants.ts
- src/app/presales/providers/deposit-provider.tsx
- src/app/presales/providers/presale-provider.tsx
- src/app/presales/types.ts
Preps change for presale closure.
> chore: Close RWA presale

- package-lock.json
- package.json
> chore: Remove analytics sdk

- package-lock.json
- package.json
> feat(deps): Upgrade tokenlists to 1.52.0

- src/app/prt-staking/components/prt-section/prt-card.tsx
- src/feature-flags.ts
Check/enforce mainnet usage on PRT widget.
> feat: Add PRT network check

- src/components/swap/components/trade-input-selector.tsx
Prevents scrolling from impacting the number input for trade size.
> fix: Number input scroll

- package-lock.json
- package.json
- src/app/analytics-provider.tsx
- src/lib/hooks/use-analytics.ts
* Updates to new 0xarc SDK (after renaming of company from arcx)
Note that the docs still use the old urls:
* https://www.npmjs.com/package/@0xarc-io/analytics
* https://github.com/0xarc-io/analytics-sdk
> build: update to new 0xarc sdk

- src/app/leverage/components/leverage-widget/components/fees.tsx
- src/app/leverage/components/leverage-widget/components/leverage-selector.tsx
- src/app/leverage/components/leverage-widget/components/token-display.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/selectors/base-asset-selector.tsx
- src/app/leverage/components/selectors/network-selector.tsx
- src/app/leverage/components/selectors/selector-button.tsx
- src/app/leverage/components/stats.tsx
- src/app/leverage/components/title.tsx
- src/app/leverage/components/your-tokens.tsx
- src/app/leverage/constants.ts
- src/app/leverage/page.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/types.ts
- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/app/leverage/utils/get-leverage-base-token.ts
- src/app/leverage/utils/get-leverage-type.ts
- src/components/banners/banner.tsx
- src/components/swap/components/transaction-review/components/from-to.tsx
* Adds Ethereum support to Leverage UI
* Fixes arrow alignment in tx review
> feat: add ethereum to leverage ui

- src/app/prt-staking/components/faq-section/index.tsx
> fix: Safe FAQ copy

- package-lock.json
- package.json
- src/app/layout.tsx
- src/lib/utils/wagmi.ts
> next 14 upgrade

- src/app/leverage/provider.tsx
* Fixes a delay when clicking the review button (caused by wrongly handling the loading state)
> fix: delay for tx review in leverage ui

- src/app/legacy/providers/redeem-provider.tsx
* Adds using `useQuery` for fetching legacy quotes
> feat: use query

- next.config.js
- src/app/providers.tsx
- src/lib/utils/wagmi.ts
add safe connector to wagmi config, as its not included by default
> Fix: Safe App

- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/components/header/network-select.tsx
- src/components/smart-trade-button/index.tsx
- src/lib/hooks/use-query-params.ts
Changing the input/output tokens sell/buy now updates leverage queryParams
> Feature: Add updating leverage queryparams based on leveragewidged config

- src/app/leverage/components/faq-section/index.tsx
Removes an outdated FAQ and updates others mentioning ARB specifically.
> fix: Update leverage FAQ

- package-lock.json
- package.json
- src/app/api/quote/route.ts
* Adds a FlashMint Quote API concept to prepare for potentially opening to external partners
```typescript
interface IndexQuoteRequest {
chainId: number
account: string
inputToken: string
outputToken: string
inputAmount?: string // either input or output amount must be set*
outputAmount?: string // either input or output amount must be set*
slippage: number
}
```
\* depends on whether you're minting (output token is index) or redeeming (input token is index)
```json
{
"chainId": 1
"account": "0x0"
"inputToken": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
"outputToken": "0x54EE8A49155F701F0d5Ff088CD36fbBF1a5B9f44"
"outputAmount": "100000000000000000000"
"slippage": 0.1
}
```
```json
{
"chainId": 1
"account": "0x0"
"inputToken": "0x54EE8A49155F701F0d5Ff088CD36fbBF1a5B9f44"
"outputToken": …
```
> feat: add quote api concept

- src/app/leverage/page.tsx
Updates the survey id and tweaks styling for the button.
> chore: Update survey id

- src/app/leverage/provider.tsx
Use the correct decimals for navchange.
> fix: Use correct decimals on navchange

- src/app/leverage/components/your-tokens.tsx
Fixed history blockexplorer url
> FIX: history - blockexplorer url

- src/app/leverage/components/leverage-widget/index.tsx
> feat: show balances for currencies in leverage ui

- src/app/api/quote/route.ts
- src/app/legacy/components/redeem-widget/use-formatted-data.tsx
- src/app/legacy/providers/redeem-provider.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/use-formatted-data.tsx
- src/app/presales/components/pre-sale-widget/use-formatted-data.tsx
- src/app/presales/providers/deposit-provider.tsx
- src/components/swap/components/select-token-modal.tsx
- src/components/swap/components/transaction-review/provider.tsx
- src/components/swap/components/transaction-review/types.ts
- src/components/swap/hooks/use-swap/formatters/index.ts
- src/components/swap/hooks/use-swap/formatters/result.ts
- src/components/swap/hooks/use-swap/index.tsx
- src/components/swap/hooks/use-swap/use-formatted-balance.tsx
- src/components/swap/index.tsx
- src/constants/icreth.ts
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/types.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
- src/lib/hooks/use-best-quote/utils/issuance/issuance-quote.ts
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
- src/lib/hooks/use-best-quote/utils/issuance/redemption-quote.ts
- src/lib/hooks/use-best-quote/utils/quote-results.test.ts
- src/lib/hooks/use-wallet.ts
- src/lib/utils/abi/interfaces.ts
- src/lib/utils/costs.test.ts
- src/lib/utils/gas-estimatooor.test.ts
- src/lib/utils/gas.ts
- src/lib/utils/simulator.ts
* Adds using new quote api for flash mint quotes
* Fixes Quote API using test value for index token amount
> feat: use flash mint quote api

- package-lock.json
- package.json
- src/lib/hooks/use-token-price.ts
* Fixes balances for DATA and GMI in legacy page (they were missing in tokenlists)
> fix: balances for data and gmi in legacy

- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
* Removes console logging from sentry
> chore: avoid logging console in sentry

- src/components/charts/price-xy-chart.tsx
- src/components/charts/tvl-xy-chart.tsx
- src/components/charts/use-chart-data.ts
Adds sampling logic to get more data granularity on 1D and 1M time frames.
> feat: chart frequency improvements

- src/app/leverage/page.tsx
Updates the height of the chart to be fixed in height.
> fix: leverage chart height

- src/app/earn/constants.ts
- src/constants/tokens.ts
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
- src/lib/utils/index.ts
> refactor: remove obsolete token props

- src/app/leverage/components/leverage-widget/components/fees.tsx
Updates carry sign to be negative.
> fix: Update carry sign

- src/app/leverage/provider.tsx
> Hotfix: Base Asset Selector resetting indefinitely.

- src/components/swap/components/select-token-modal.tsx
Cherry pick fix of light / dark bg for chakra modal 
> add explicit light and dark background (#1659)

- src/app/swap/[[...path]]/path-resolver.test.ts
- src/constants/tokenlists.ts
- src/lib/utils/tokens.ts
* Removes all earn and leverage tokens from swap (as they are now more prominent under the new sections)
> refactor: remove from swap

- package-lock.json
- package.json
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/legacy/components/redeem-widget/use-formatted-data.tsx
- src/app/legacy/config.ts
- src/app/legacy/polygon.ts
- src/app/legacy/providers/redeem-provider.tsx
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
- src/lib/hooks/use-token-price.ts
- src/lib/utils/wagmi.ts
* Adds deprecated and delevered polygon tokens to legacy
> feat: add polygon flis to legacy

- README.md
- package-lock.json
- package.json
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/legacy/components/redeem-widget/use-formatted-data.tsx
- src/app/legacy/config.ts
- src/app/legacy/polygon.ts
- src/app/legacy/providers/redeem-provider.tsx
- src/app/leverage/components/your-tokens.tsx
- src/app/leverage/constants.ts
- src/app/leverage/provider.tsx
- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/app/leverage/utils/get-leverage-base-token.ts
- src/app/leverage/utils/get-leverage-type.ts
- src/constants/tokens.ts
- src/lib/hooks/use-best-quote/utils/available.test.ts
- src/lib/hooks/use-best-quote/utils/available.ts
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
- src/lib/hooks/use-best-quote/utils/quote-results.test.ts
- src/lib/hooks/use-token-price.ts
- src/lib/utils/wagmi.ts
* Adds new ratio tokens to leverage UI
Note that currently the logos and price feeds are missing as they are WIP. ⚠️ 
> feat: add ratio tokens

- src/app/api/leverage/history/route.ts
- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/app/products/utils/formatters.ts
- src/components/charts/price-chart.tsx
- src/components/charts/price-xy-chart.tsx
- src/components/charts/tvl-xy-chart.tsx
- src/components/charts/use-chart-data.ts
- src/lib/hooks/use-token-history.ts
> FIX: usage of tokenlists refactored alchemy history fetching

- src/components/swap/hooks/use-tokenlists.ts
- src/components/swap/index.tsx
- src/constants/tokenlists.ts
- src/lib/utils/tokens.ts
Adds yield tokens to swap interface.
> feat: swap yield tokens

- src/app/earn/provider.tsx
- src/app/legacy/providers/redeem-provider.tsx
* Fixes earn query issues by introducing `useQuery` to the earn provider
> fix: earn query issues

- src/components/header/connect.tsx
- src/components/header/index.tsx
- src/components/header/link.tsx
- src/components/header/logo.tsx
- src/components/header/more-nav.tsx
- src/components/header/network-select.tsx
Decreases sizing on the header per designs.
> feat: header styling v2

- src/app/earn/use-formatted-data.tsx
- src/app/leverage/constants.ts
- src/app/leverage/provider.tsx
- src/app/leverage/use-formatted-data.tsx
- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/app/products/constants/tokens.ts
- src/app/products/utils/trade-path.ts
> feat: enable ratio tokens

- src/app/products/components/product-list.tsx
- src/app/products/components/product-panel.tsx
- src/app/products/constants/tokens.ts
- src/app/products/types/product.ts
Adds the leverage section to the products page.
> feat: leverage product list

- src/app/leverage/provider.tsx
Updates the leverage provider to use `useQuery` (compare to recent changes in [earn](https://github.com/IndexCoop/index-app/pull/1687/files) provider)
> feat: use query in leverage

- src/components/header/connect.tsx
- src/components/header/index.tsx
- src/components/header/link.tsx
- src/components/header/network-select.tsx
Updates styling on header to be larger.
> fix: leverage v2 header styling

- src/app/leverage/components/trading-view-widget.tsx
- src/app/leverage/page.tsx
Undo height change and fix btceth chart.
> fix: leverage v2 tweaks

- src/app/leverage/components/leverage-widget/index.tsx
- src/components/receive/index.tsx
- src/components/swap/components/selector-button.tsx
Adds the output amount in USD for the Leverage page.
> feat: receive amount usd

- src/app/earn/provider.tsx
* Quick fix for icETH slippage being too low
> fix: iceth slippage

- src/app/earn/provider.tsx
> fix: iceth

- biome.json
- src/app/earn/provider.tsx
- src/app/leverage/components/stats/leverage-selector-container.tsx
- src/app/leverage/components/stats/use-quick-stats.tsx
- src/app/leverage/provider.tsx
- src/lib/hooks/use-prepare-transaction-review.ts
- src/lib/hooks/use-quote-result/best-quote.ts
- src/lib/hooks/use-quote-result/index.ts
- src/lib/hooks/use-transaction-review.ts
* Refactors quote results into a hook
* Updates earn and leverage providers accordingly
* Adds `usePrepareTransactionReview`
Note: Swap will not use the new hook as it's probably removed at some point and with it `useBestQuote`
> refactor: quotes hook

- src/app/earn/components/earn-widget/index.tsx
- src/app/earn/layout.tsx
- src/app/earn/provider.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/layout.tsx
- src/app/leverage/provider.tsx
- src/lib/hooks/use-quote-result/index.ts
- src/lib/providers/slippage/index.tsx
> feat: add slippage config to earn and leverage

- .github/workflows/unit-tests.yml
- README.md
> chore: lint peristent user data

- src/components/smart-trade-button/index.tsx
- src/components/swap/index.tsx
- src/lib/utils/tokens.ts
* Removes redemption restriction for restricted persons (only mints are restricted now)
> feat: remove redemption restriction

- src/app/leverage/constants.ts
- src/lib/utils/tokens.ts
* Adds cbBTC as currency token on Base
> feat: add cbbtc

- src/app/earn/components/earn-widget/index.tsx
- src/constants/slippage.ts
- src/lib/providers/slippage/index.tsx
- src/lib/utils/slippage.test.ts
* Updates slippage correctly when changing earn tokens (leverage tokens don't have any defaults)
> fix: update slippage

- src/app/api/quote/swap/route.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
* Adds a new internal route for swap quotes and updates index quote accordingly.
* Swap quotes should work as before. ✅ 
> chore: add using swap quotes from api v2

- src/app/swap/[[...path]]/path-resolver.test.ts
- src/app/swap/[[...path]]/path-resolver.ts
- src/lib/providers/selected-token-provider/index.tsx
* Disables buying hyETH/dsETH via Swap
> chore: disable hyeth/dseth swapping

- src/app/leverage/components/portfolio-widget/table.tsx
> changed table overflow to auto

- src/app/earn/constants.ts
- src/app/earn/provider.tsx
- src/app/presales/constants.ts
- src/app/presales/providers/presale-provider.tsx
- src/app/products/constants/tokens.ts
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
* Removes icUSD where possible
* Moves icUSD to /swap
> chore: deprecate icusd

- src/components/swap/components/transaction-review/components/review.tsx
- src/components/swap/components/transaction-review/provider.tsx
* Hides override option for now (to be able to quickly re-introduce if needed)
> chore: hide override

- next.config.js
- src/components/header/index.tsx
- src/components/header/logo.tsx
* Updates /leverage to be the landing page
* Hides product page from navigation bar
> chore: make leverage landing page

- src/app/earn/components/chart-tabs.tsx
- src/app/earn/page.tsx
- src/app/earn/provider.tsx
- src/app/products/components/product-panel.tsx
- src/components/charts/use-chart-data.ts
- src/lib/utils/api/index-data-provider.ts
- src/lib/utils/apy.ts
Enables the APY chart and adds support to fetch multiple values per metric.
> feat: APY updates

- src/components/header/network-select.tsx
Fix network switch text color in light mode.
> fix: earn network switch text

- src/app/leverage/constants.ts
- src/app/leverage/provider.tsx
Order `ratios` so that 3x appears first, then 2x, then -1.
> feat: leverage default to 3x

- env.d.ts
- package-lock.json
- package.json
- src/app/analytics-provider.tsx
- src/app/leverage/components/leverage-widget/components/leverage-selector.tsx
- src/app/leverage/components/portfolio-widget/portfolio-widget.tsx
- src/app/leverage/components/stats/leverage-ratio-item.tsx
- src/app/leverage/components/stats/market-selector.tsx
- src/components/selectors/buy-sell-selector-button.tsx
- src/lib/hooks/use-analytics.ts
- src/lib/hooks/use-quote-result/index.ts
Removes `react-ga4` in favor of next lib, updates event calls.
> chore: Use @next google analytics lib

- src/app/earn/components/earn-widget/components/summary.tsx
- src/app/earn/use-formatted-data.tsx
- src/app/leverage/components/leverage-widget/components/summary.tsx
- src/app/leverage/use-formatted-data.tsx
- src/lib/hooks/use-best-quote/types.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
> feat: add price impact

- src/app/leverage/components/leverage-widget/components/buy-sell-selector.tsx
Updates open/close button labels to buy/sell.
> chore: update to buy/sell

- src/app/earn/constants.ts
- src/lib/hooks/use-token-price.ts
> feat: add wsteth15x

- src/lib/utils/api/database.ts
> FIX: wsteth underlying

- .vscode/settings.json
- src/components/header/connect.tsx
- src/components/header/index.tsx
- src/components/header/more-nav.tsx
- src/components/header/network-select.tsx
Updates dark header background and interactive elements around it.
> chore: update dark head bg

- src/app/leverage/page.tsx
Adjusts margin between header and page, as well as between quick stats and chart on smaller screens.
> chore: Tweak leverage spacing

- src/app/globals.css
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/light-effect.tsx
- src/app/leverage/layout.tsx
- src/components/faq/faq-list.tsx
- src/components/footer/index.tsx
- src/components/header/index.tsx
> FEAT: pimped backgrounds

- src/app/earn/constants.ts
- src/app/earn/provider.tsx
Updates currency tokens for icETH to (W)ETH only - as other currency tokens would fail quotes due to contract limitations.
> chore: update get currency tokens for iceth

- src/components/swap/components/trade-details/index.tsx
- src/components/swap/index.tsx
Refactors the Chakra `Box` usages.
> chore: refactor chakra box

- src/components/swap/components/select-token-modal.tsx
- src/components/swap/components/warning.tsx
Refactors the Chakra `Image` and `Link` usages.
> chore: refactor chakra image/link

- src/app/leverage/components/faq-section/index.tsx
Updates trade questions for new SOL/SUI tokens.
> feat: updated trade questions

- src/app/api/leverage/history/route.ts
- src/lib/utils/api/database.ts
> FIX: save asset underlying properly

- package-lock.json
- package.json
- src/lib/utils/api/database.ts
Simplifying a bunch of things with the new tokenlist version
> Feat: Use new tokenlist

- src/app/earn/constants.ts
> FIX: usdt symbol management

- src/app/earn/layout.tsx
> No  cache policy - for earn api request

- src/app/store/trade-machine.ts
- src/lib/hooks/use-quote-result/index.ts
> try fixing sticky quote

- package-lock.json
- package.json
> Chore: update viem, wagmi, reown/appkit stuff

- src/app/leverage/components/stats/use-quick-stats.tsx
Fixes an issue where the address/chain don't match in the API stats query.
> fix: stats query

- src/app/api/quote/utils.ts
- src/app/api/slippage/[...slug]/route.ts
- src/app/earn/components/earn-widget/index.tsx
- src/app/earn/provider.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/app/store/trade-machine.ts
- src/lib/hooks/use-quote-result/index.ts
> FEAT: Widget Quote Error handling

- src/app/earn/components/earn-widget/index.tsx
> FEAT: Earn Widget Outtoken selector

- src/app/earn/layout.tsx
> Chore: Add footer to earn

- src/app/api/slippage/[...slug]/route.ts
> Chore: use apiv2 slippage endpoint

- src/app/leverage/components/portfolio-widget/portfolio-widget.tsx
Makes positions and history dropdowns.
> feat: dropdown positions/history

- src/app/earn/components/earn-widget/components/trade-input-selector.tsx
- src/app/earn/components/earn-widget/index.tsx
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/leverage-widget/trade-input-selector.tsx
- src/app/prt-staking/components/prt-section/prt-widget.tsx
- src/components/settings/index.tsx
- src/components/swap/components/trade-input-selector.tsx
- src/components/swap/index.tsx
Refactors the chakra `Input` and `Popover` usages.
> feat: chakra popover/input refactor

- src/app/earn/components/balance-card.tsx
- src/app/earn/components/product-card.tsx
- src/components/footer/footer-link.tsx
- src/components/header/index.tsx
- src/components/header/link.tsx
> FIX: earn navigation speedup

- src/app/prt-staking/components/prt-section/prt-popup.tsx
- src/app/prt-staking/components/prt-section/safe-sign-button.tsx
- src/app/prt-staking/components/prt-section/select-safe-modal.tsx
- src/app/prt-staking/components/prt-section/widget-header.tsx
- src/components/swap/components/select-token-modal.tsx
- src/components/swap/components/transaction-review/index.tsx
- src/components/trade-button/index.tsx
Refactors the Chakra `Modal` to `Dialog`
> feat: chakra modal refactor

- src/app/earn-old/provider.tsx
- src/app/earn/components/earn-widget/index.tsx
- src/app/earn/provider.tsx
- src/app/legacy/components/redeem-widget/components/receive.tsx
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/leverage-widget/trade-input-selector.tsx
- src/app/leverage/provider.tsx
- src/app/store/trade-machine.ts
- src/components/receive/index.tsx
- src/components/swap/components/transaction-review/components/submission-result.tsx
- src/lib/hooks/use-quote-result/index.ts
> Fix: Sticky Quote

- src/components/swap/components/transaction-review/components/submission-result.tsx
> FIX: trade success window denominator

- src/app/api/quote/route.ts
- src/app/api/quote/utils.ts
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-quote-result/index.ts
> add error messages based on api returns

- src/app/swap/[[...path]]/path-resolver.ts
- src/components/swap/hooks/use-swap/index.tsx
- src/components/swap/hooks/use-tokenlists.ts
- src/components/swap/index.tsx
- src/constants/slippage.ts
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/hooks/use-balance.ts
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/available.test.ts
- src/lib/hooks/use-best-quote/utils/available.ts
- src/lib/providers/selected-token-provider/index.tsx
- src/lib/providers/slippage/index.tsx
- src/lib/utils/gas-defaults.ts
- src/lib/utils/slippage.test.ts
- src/lib/utils/slippage.ts
- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
* Updates slippage default for icETH
* Removes base and icUSD from /swap
* Fixes balances for /swap 
* Removes all indices token constants
> chore: update iceth auto slippage

- src/app/legacy/components/redeem-widget/index.tsx
* Removes tx review for legacy redemptions as it confuses users in terms of receiving tokens (popup can not display mutli output tokens)
* Adds executing tx directly from submit button
> remove tx review modal for legacy. execute tx directly

- src/app/earn/components/wsteth-banner.tsx
- src/app/earn/product/[address]/page.tsx
* Adds wstETH15x banner on icETH product page
> feat: add wsteth15x banner

- src/app/leverage/constants.ts
- src/app/leverage/provider.tsx
- src/app/leverage/utils/get-leverage-base-token.ts
- src/lib/hooks/use-token-price.ts
- src/lib/utils/tokens.ts
> feat: add usol3x usui3x

- src/app/leverage/components/leverage-widget/components/summary.tsx
- src/app/leverage/use-formatted-data.tsx
- src/lib/hooks/use-best-quote/types.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
Adds price impact warning for leverage quotes.
> add price impact warning

- src/lib/hooks/use-quote-result/index.ts
- src/lib/providers/slippage/index.tsx
> Feat: reset quote on slippage change

- src/app/earn/provider.tsx
- src/app/leverage/components/leverage-widget/components/summary.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/use-formatted-data.tsx
- src/lib/hooks/use-best-quote/types.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
- src/lib/providers/slippage/index.tsx
* Updates quote output for better comprehension
* Re-enables using auto slippage endpoint
> feat: update quote output

- src/app/leverage/components/leverage-widget/components/summary.tsx
Adds tooltips for the summary in leverage.
> feat: add tooltips

- src/app/earn/components/earn-widget/components/summary.tsx
Fixes earn summary max amount spent value.
> fix: earn summary for max amount spent
