IndexCoop/index-app

- src/components/trade/flashmint/DirectIssuance.tsx
- src/components/trade/flashmint/index.tsx
Adds dollar values for the index and input/ouput token in FlashMint, so users can better comprehend the values they are getting.
&nbsp;
&nbsp;
> Add dollar values to FlashMint

- src/components/trade/flashmint/DirectIssuance.tsx
- src/components/trade/flashmint/index.tsx
- src/constants/tokens.ts
- src/hooks/useTradeTokenLists.test.ts
- src/hooks/useTradeTokenLists.ts
- src/utils/tokens.ts
Update so deprecated indices are no longer mintable via FlashMint (redeem only).
&nbsp;
&nbsp;
> Deprecate MNYe, DATA, GMI, FLI-P

- src/components/token-page/TokenPage.tsx
Adds a message at the top of a product page if the selected token is deprecated.
&nbsp;
> Add deprecation message to product pages

- src/components/trade/swap/index.tsx
- src/utils/tokens.ts
Updates `Swap` to prevent minting of deprecated tokens (now redeem only). Leverages existing `tokenIsMintable` function.
&nbsp;
> Update swap to prevent minting of deprecated tokens

- src/utils/tokens.ts
Fixes Index token accidentally showing deprecation message.
&nbsp;
> Fix Index token should be mintable

- src/components/trade/_shared/SelectTokenModal.tsx
- src/components/trade/flashmint/index.tsx
- src/constants/tokens.ts
iETHFLIP: ✅
iBTCFLIP: too many components error
iMATICFLIP: ✅
ETH2xFLIP: errors for some 0x API calls but still shows the correct quote
BTC2xFLIP: errors for some 0x API calls but still shows the correct quote
MATIC2xFLIP: too many components error
> Reactivate 2xFLI's for redeeming

- src/components/trade/flashmint/index.tsx
- src/constants/slippage.ts
- src/providers/Slippage/index.tsx
- src/utils/slippage.test.ts
- src/utils/slippage.ts
* Adds slippage map for tokens that should use different slippage settings modifications
* Adds utility functions to get slippage modification based on different factors e.g. when the user set a custom slippage we should always use that value
New tests. ✅ 🌟 
> Add slippage mapping

- package.json
- yarn.lock
* Upgrades FlashMintSDK to v1.5.3 to get rid of some issues w/ minting/redeeming BTC2xFLI or any swap data that includes UniV3 paths.
> Upgrade flash mint sdk

- src/hooks/useTrade.ts
Currently the Trade button breaks when changing the network without reloading the page. 
I.e. after switching to the new trade button clicking on "trade" does not trigger a transaction confirmation request.
This behaviour was due to the `useTrade` callback only being updated when the "address" changed but not the chainId, resulting in mismatched chainIds between the zeroExQuote response and what was expected by the `sendTransaction` function.
To reproduce this error do the following:
1. Open the app and connect wallet
2. Trigger swap but reject transaction signature in wallet
3. Switch network (but not address)
4. Try swapping on new network.
On the current master version step 4 does not trigger a transaction / signature request in the wallet. 
With this update this should be fixed
- I …
> Fix broken trade button when changing the network

- src/hooks/useTrade.ts
Sometimes the "spendTokenBalance" seemed to be incorrect when trying to execute the trade. (i.e. the token balances had not updated yet and was still at 0 so the trade would not get executed )
> Add getTokenBalance as memoization trigger

- src/app/swap/[[...path]]/page.tsx
- src/components/supply/RethSupplyCap.tsx
- src/components/supply/index.tsx
- src/components/supply/useRethSupply.ts
- src/components/trade/flashmint/index.tsx
* Updates icRETH supply cap visualization
* Now uses min of available icRETH based on Aave and Index supply cap
&nbsp;
&nbsp;
> feat: update supply cap

- src/components/trade/_shared/QuickTradeFormatter.ts
- src/components/trade/swap/index.tsx
* Removes obsolete NAV price in trade details.
> remove nav from trade details

- src/components/swap/hooks/use-swap/formatters/index.test.ts
- src/components/swap/hooks/use-swap/formatters/index.ts
- src/components/swap/hooks/use-swap/index.tsx
* Updates the single token prices displayed in the trade details section to be determined by dividing the quantities
> update formatted single token prices

- .eslintrc.json
- src/app/vaults/page.tsx
- src/app/vaults/vault-token-card.tsx
- src/components/header/header-v2.tsx
- src/components/swap/components/transaction-review/components/from-to.tsx
- src/components/swap/components/transaction-review/components/override.tsx
- src/components/swap/components/transaction-review/components/simulation.tsx
- src/components/swap/components/transaction-review/index.tsx
- src/components/swap/hooks/use-swap/index.tsx
- src/components/swap/index.tsx
- src/components/trade-button/index.tsx
- src/lib/styles/theme.ts
* Adds the eslint `import/oder` rule to keep imports sorted the right way (defined in `groups`)
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
> add import order rule

- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/index-token-amount.test.ts
- src/lib/hooks/use-best-quote/utils/index-token-amount.ts
Thanks to @edkim fix (https://github.com/IndexCoop/index-app/pull/969), I realized that the whole `getIndexTokenAmount` could be simplified. Because the dex data is actually not relevant at all. (This was more relevant back in the days when the app worked differently.)
So this cleans up the function and also introduces `bigint`. Tests are updated accordingly. ✅ 
> refactor: simplify index token amount

- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/index-token-amount.test.ts
- src/lib/hooks/use-best-quote/utils/index-token-amount.ts
Take the absolute value of `dexSwapOption.estimatedPriceImpact` because it's usually a negative number. This gives a much better approximate index token amount when minting.  
https://cdn.discordapp.com/attachments/930566173614022717/1199063142777491526/DevTools_-_localhost_3000_swap.png?ex=65c12d92&is=65aeb892&hm=df23b545448aea86136412417ff6d431c0fa275ce3fe7cb0e4c2e3e8eac03ea1&
> Fix: Take absolute value of Dex Swap price impact

- src/components/swap/hooks/use-trade-button-state.tsx
- src/components/swap/hooks/use-trade-button.tsx
- src/components/swap/index.tsx
* Disables minting of ETH2x-FLI and BTC2x-FLI by disabling trade button w/ `Not available`
> disable minting of FLIs

- src/components/swap/components/transaction-review/components/bottom-message.tsx
- src/components/swap/components/transaction-review/components/contract-section.tsx
- src/components/swap/components/transaction-review/components/review.tsx
- src/components/swap/components/transaction-review/index.tsx
- src/components/swap/components/transaction-review/provider.tsx
* Refactors transaction review to prepare for looking into simulation/override issues
* Updates a few of the review components to use tailwind only (more to follow in future PRs)
* Should work as before
> refactor: transaction review

- src/components/swap/components/transaction-review/components/override.tsx
- src/components/swap/components/transaction-review/provider.tsx
* Should fix overriding in transaction review by adding an additional check for not re-running simulations
* To test just `return false` in `simulateTrade` which simulates a failed tx simulation
* When getting a quote e.g. ETH-ETH2x and opening up the transaction review...
* Submitting should fail the simulation and show `override`
* Unchecked `override` should make the submit button disabled
* Checking `override` should let the user submit the tx nevertheless
```typescript
async function simulateTrade(): Promise<boolean> {
return false
...
```
- I …
> fix: override simulation

- src/app/legacy/components/redeem-widget/components/deposit-withdraw-selector.tsx
- src/app/legacy/components/redeem-widget/components/summary.tsx
- src/app/legacy/components/redeem-widget/components/title-logo.tsx
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/legacy/components/redeem-widget/styles.css
- src/app/legacy/components/redeem-widget/use-formatted-data.tsx
- src/app/legacy/layout.tsx
- src/app/legacy/page.tsx
- src/app/legacy/providers/redeem-provider.tsx
- src/lib/utils/tokens.ts
* Adds a simple page for redeeming legacy products ([/legacy](https://index-app-git-feat-add-legacy-redeem-index-coop.vercel.app/legacy)) - currently hard-coded to icRETH
> feat: add legacy redeem

- next.config.js
- src/app/presales/components/pre-sale-token-card/status-chip.tsx
- src/app/presales/constants.ts
* Disables presale until launch
* Adds config for redirecting `/pre-sales` to `/presales` (permantently)
> disable presale

- src/app/presales/components/pre-sale-token-card/index.tsx
* Removes obsolete symbol for formatted total deposits
> remove symbol

- package-lock.json
- package.json
- src/app/legacy/providers/redeem-provider.tsx
- src/app/presales/providers/deposit-provider.tsx
- src/app/providers-lite.tsx
- src/app/providers.tsx
- src/components/swap/index.tsx
- src/lib/hooks/use-approval.ts
- src/lib/hooks/use-balance.ts
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-network.ts
- src/lib/hooks/use-simulate-quote.ts
- src/lib/hooks/use-trade.ts
- src/lib/hooks/use-wallet.ts
- src/lib/utils/gas-estimatooor.test.ts
- src/lib/utils/wagmi.ts
* Migrates RainbowKit, viem, wagmi to the latest versions (from v1 to v2)
ℹ️ Most breaking changes were in RainbowKit and wagmi. viem was pretty straight forward.
* https://wagmi.sh/react/installation
* https://wagmi.sh/react/guides/migrate-from-v1-to-v2
* https://www.rainbowkit.com/docs/installation
* https://www.rainbowkit.com/docs/migration-guide
* Everything should work as before. The whole app needs to be tested.
> build: migrate rainbowkit viem wagmi

- src/app/swap/layout.tsx
- src/components/banners/index.tsx
* Adds banner to advertise bridging MVI and DPI to Arbitrum
> add banner

- src/app/legacy/components/redeem-widget/index.tsx
- src/app/legacy/providers/redeem-provider.tsx
- src/lib/hooks/use-best-quote/utils/issuance/issuance-quote.ts
- src/lib/utils/tokens.ts
* Adds `gtcETH` and `BED` to legacy redeem to provide an alternative path for users to redeem those products
* Adds select token modal to legacy widget (before it was only one token)
> feat: add gtceth and bed to legacy redeem

- src/app/leverage/components/leverage-widget/index.tsx
- src/components/smart-trade-button/index.tsx
Hidden warnings is triggering a re-render that interrupting other cycles. 
> fix: Hidden warnings rendering

- src/components/smart-trade-button/index.tsx
Fixes an issue where a warning set doesn't get removed on the leverage interface.
> fix: Reset warnings if none set

- src/components/swap/hooks/use-swap/formatters/index.ts
- src/lib/utils/index.ts
* Updates balance decimals to be `3` for a better display of smaller numbers
* Removes obsolete wei utility function
> feat: improve balance formatting

- src/app/presales/components/pre-sale-widget/use-formatted-data.tsx
- src/app/presales/components/pre-sale-widget/use-rewards.tsx
Adds `tokenAddress` query parameter (currently ignored by endpoint) to support returning PRT values for different tokens.
> feat: PRT query param

- README.md
- hardhat.config.js
- package-lock.json
- package.json
- src/app/presales/components/faq-section/index.tsx
- src/app/presales/components/popup/index.tsx
- src/app/presales/components/pre-sale-section/disclaimer.tsx
- src/app/presales/components/pre-sale-section/index.tsx
- src/app/presales/components/pre-sale-widget/index.tsx
- src/app/presales/constants.ts
- src/constants/tokens.ts
- src/lib/hooks/use-best-quote/utils/issuance/issuance-quote.ts
- src/lib/utils/gas-defaults.ts
- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
* Updates RWA presale data using deployed [token](https://etherscan.io/token/0x7f5f1A44dd6f88cCb54Fe879e144dF644A4aDa24)
* Updates issuance code as necessary for RWA
* Updates tokenlists
* Removes obsolete default chain on token type
* https://gov.indexcoop.com/t/iip-188-launch-the-real-world-asset-index-rwa-presale/4792
> feat: add rwa issuance

- src/app/presales/constants.ts
* Fixes wrong end date for presale of RWA
https://gov.indexcoop.com/t/iip-188-launch-the-real-world-asset-index-rwa-presale/4792#presale-details-11
> fix: rwa presale end date

- src/app/presales/components/pre-sale-widget/index.tsx
- src/app/presales/providers/deposit-provider.tsx
- src/lib/hooks/use-best-quote/utils/index-token-amount.ts
- src/lib/hooks/use-token-price.ts
* Adds flash mint to RWA presale - so other tokens than wstETH can be used as input
> feat: add flashmint to presale

- src/components/swap/components/trade-details/trade-info.tsx
* Fixes visual bug for tooltips
> fix: tooltips display bug

- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/quote-results.test.ts
- src/lib/hooks/use-best-quote/utils/quote-results.ts
* A user reported to have been seeing wrong quotes (flashmint on Arbitrum which shouldn't exist) after switching from Mainnet to Arbitrum
* Fix by always resetting quotes when switching chains
> fix: quote results when switching chains

- src/app/legacy/providers/redeem-provider.tsx
- src/app/presales/providers/deposit-provider.tsx
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
- src/lib/utils/costs.test.ts
- src/lib/utils/gas-estimatooor.test.ts
- src/lib/utils/index.test.ts
- src/lib/utils/index.ts
* Replaces `toWei` with already existing internal `parseUnits` 
Missing part to close #1350 
> refactor: replace to wei

- src/app/leverage/provider.tsx
- src/lib/hooks/use-balance.ts
Fixes the superfluous `balanceOf` calls. Additional refactoring would be needed to support skipping all balance calls against invalid tokens for a particular chain.
> fix: Empty ERC20 balance call

- src/app/leverage/utils/fetch-leverage-token-prices.ts
- src/lib/hooks/use-best-quote/utils/flashmint.ts
- src/lib/hooks/use-best-quote/utils/index-quote.ts
Avoids calling `parseFloat` on a number that could contain a comma as anything after it would get truncated (`formatWeiAmount` could return a number with a comma in it).
> fix: Amount parsing

- src/app/products/components/product-list.tsx
- src/app/products/components/product-row-item/product-row-item-desktop.tsx
Sort Products by TVL 
This is just a proposal, but demonstrates how useQuery helps out with a lot of things. The pr implementation will result in refetching every 30 seconds, but also if the user refocuses the window, it will automatically rerun so we might as well remove the constant refetch (let's discuss). The result will be cached under the provided key, upon multiple fetches from different places, the cache will be used, and requests with the same key will also be deduplicated. LMK what do you think.
I know we've talked about the SSR ordering way, but it seems like since the ProductRowItem component already has a skeleton loader, so I felt like its fine this way. I've just added 'tvl' into the `select` mapping of useQuery if sortBy is undefined.
> Feature: Default sort by TVL

- src/app/leverage/utils/get-leverage-type.ts
- src/lib/hooks/use-token-history.ts
With safe wallets there is an issue of the history widget that 'Close'-s are shown as 'Transfer'-s. This is a test branch to see if adding the counterpart of isMint solves this issue. (SPOILER: it does)
> Feature: Address safe wallet closes on TX History

- src/app/legacy/components/redeem-widget/components/receive.tsx
- src/app/legacy/components/redeem-widget/index.tsx
- src/app/legacy/components/redeem-widget/use-formatted-data.tsx
- src/app/legacy/providers/redeem-provider.tsx
- src/app/legacy/providers/utils.ts
- src/app/legacy/types.ts
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
* Adds support for displaying multiple output tokens e.g. BED (legacy tokens that have not been rebalanced)
> feat: add multi component receive for legacy UI

- src/lib/hooks/use-query-params.ts
Added a default queryParam in case the user is arriving directly at the /leverage page.
> FIX: added default queryparam if coming directly to leverage

- next.config.js
- src/app/legacy/config.ts
- src/lib/hooks/use-best-quote/utils/issuance/legacy-quote.ts
* Adds ic21 to legacy page (to already be able to redeem via issuance contract now)
> feat: add ic21 to legacy

- package-lock.json
- package.json
- src/app/prt-staking/components/prt-section/prt-widget.tsx
- src/components/tooltip/index.tsx
- src/components/trade-button/index.tsx
Adds a new `Tooltip` component to eventually support pulling out Chakra and updates the label/tooltip when `canStake` is set to `false`.
> feat: canStake messaging

- src/components/external/mava-script.tsx
- src/components/tooltip/index.tsx
- src/components/trade-button/index.tsx
The Mava widget isn't loading properly on the first load of the `/leverage` page, but would if you navigate to it from another page first - fixed by moving to `next/script`.
Also saw a nextjs hydration error related to the tooltip trigger that was added (button was a descendant of button) - updated to remove the inner button.
> fix: Mava loading on /leverage

- src/app/leverage/provider.tsx
- src/lib/hooks/use-network.ts
Updates the logic to call `switchChain` on load if `queryNetwork` is set and ensures the centrally set `chainId` is what gets used throughout the provider.
> fix: Chain switch

- src/app/earn/use-formatted-data.tsx
- src/app/leverage/use-formatted-data.tsx
* Fixes displaying small numbers for quote output amounts 
> fix: output amount for small numbers

- src/components/header/network-select.tsx
Add a small delay, to deal with a flicker, while switching networks without confirmation.
> FIX: add 1s delay for the network message to appear

- src/app/earn/components/faq-section/index.tsx
- src/app/earn/components/stat-metric.tsx
- src/app/leverage/components/leverage-widget/components/buy-sell-selector.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/leverage-widget/styles.css
- src/app/leverage/components/stats/index.tsx
- src/app/leverage/components/stats/leverage-selector-container.tsx
- src/app/leverage/components/stats/stats-metric.tsx
- src/app/leverage/page.tsx
- src/components/selectors/buy-sell-selector-button.tsx
* Adds leverage ratio submenu
* Adds some styling updates for the leverage trade widget
* Fixes padding for quick stats header
Note that the assets for the networks are in https://github.com/IndexCoop/index-app/pull/1685 but we would probably not release the lev ratio submenu yet - as that whole section would be hidden (due to missing data). ⚠️ 
> feat: add leverage submenus

- src/app/leverage/types.ts
- src/app/leverage/utils/fetch-leverage-token-prices.ts
Fixes how we calculate `leverageType`
> fix: tokens current leverage

- src/app/leverage/provider.tsx
* Fix leverage quotes when selecting output currencies (isMinting: false)
> fix: leverage quotes when selecting output currency

- src/app/earn/provider.tsx
- src/lib/hooks/use-token-price.ts
* Fixes hyETH missing price for quotes
* Fixes reloading quotes when changing output token when redeeming
> fix: hyeth quotes

- src/app/products/components/product-row-item/product-row-item-desktop.tsx
- src/app/products/components/product-row-item/product-row-item-mobile.tsx
- src/app/products/constants/tokens.ts
- src/app/products/types/product.ts
- src/app/products/utils/formatters.ts
Add support to specify digits on the tokens listed on the product page.
> feat: product list digits

- biome.json
- src/app/api/stats/route.ts
- src/app/earn/provider.tsx
- src/app/leverage/components/leverage-widget/components/summary.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/app/leverage/components/stats/index.tsx
- src/app/leverage/components/stats/leverage-selector-container.tsx
- src/app/leverage/components/stats/use-quick-stats.tsx
- src/app/leverage/page.tsx
- src/app/leverage/provider.tsx
- src/app/leverage/use-formatted-data.tsx
- src/lib/hooks/use-prepare-transaction-review.ts
- src/lib/hooks/use-quote-result/best-quote.ts
- src/lib/hooks/use-quote-result/index.ts
* Moves more data into quick stats
> feat: enhance quick stats

- src/app/leverage/components/chart-tabs.tsx
- src/app/leverage/page.tsx
* Updates spacing between some of the components of the leverage UI
* Updates the chart tabs style to match open/close tabs of the trade widget
> feat: leverage UI remainders

- src/app/layout.tsx
Forces white background on `body` to override Chakra.
> fix: add body white fallback

- src/app/api/leverage/history/route.ts
changed to weighted average of totalPurchaseSize * underlyingAssetPrice
> Chore: Avg Entry Price Formula update

- next.config.js
- src/components/banners/leverage-banner.tsx
- src/components/header/index.tsx
- src/components/header/logo.tsx
- src/constants/paths.ts
- change /leverage links to /trade 
- change "Leverage" to "trade in navigation 
- set up re-direct from [app.indexcoop.com/leverage](https://app.indexcoop.com/leverage) to [app.indexcoop.com/trade](https://app.indexcoop.com/trade)
> feat: rename leverage to trade

- next.config.js
Hardens assets that could be loaded from github. Right now this should only be assets from the trust wallet repo e.g. https://github.com/IndexCoop/tokenlists/blob/fefcf619da04146968d33a6cae4ebe417b3d944d/src/tokenlist.json.ts#L1920
> fix: allowed github images path

- src/app/earn/components/earn-widget/index.tsx
- src/app/leverage/components/leverage-widget/index.tsx
- src/components/swap/index.tsx
- src/lib/hooks/use-gas-data.ts
- src/lib/utils/max-balance.ts
Adds max ETH balance. Requires to substract the approximate gas costs.
```
const gasCosts = gasLimit * (baseFee + maxPriorityFee)
const maxEthBalance = inputBalance - gasCosts 
```
_\* base and max priority fee are medians of the last 10 blocks fetched from the network's fee history._
* https://ethereum.org/en/developers/docs/gas/
* https://www.blocknative.com/gas-estimator
> feat: add eth max balance

- src/app/leverage/components/trading-view-chart-container.tsx
- src/app/leverage/components/trading-view-chart.tsx
Fixes an issue where the chart doesn't load on mobile, uses the `iframe_loading_compatibility_mode` setting. https://www.tradingview.com/charting-library-docs/latest/customization/Featuresets/#iframe_loading_compatibility_mode
> fix: mobile tradingview chart

- src/app/legacy/config/index.ts
- src/app/legacy/config/tokens/mainnet.ts
- src/app/products/constants/tokens.ts
- src/constants/slippage.ts
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/hooks/use-best-quote/index.ts
- src/lib/hooks/use-best-quote/utils/available.test.ts
- src/lib/hooks/use-best-quote/utils/available.ts
- src/lib/utils/gas-defaults.ts
- src/lib/utils/slippage.test.ts
- src/lib/utils/tokens.test.ts
- src/lib/utils/tokens.ts
Moves `cdETI` to legacy. Removes unnecessary references.
Did a test [transaction](https://etherscan.io/tx/0x53cf2f9c6d0b221073cf86edda518e016b7697521e0bbe8941c624ae5de8ea1e).
> chore: move cdETI to legacy

- src/app/leverage/components/trading-view-chart.tsx
Added an effect to see if the script already in the dom. We got the disconnected state because the script was already there, and the onLoad function didnt run in that case.
> FIX: TradingView chart script detection after page refresh

- src/lib/hooks/use-wallet.ts
Use appkit's function to fetch address instead of wagmi. Previously, the wagmi function seemed to cause issues here when reading safe balances.
https://docs.reown.com/appkit/react/core/hooks#useappkitaccount
> use appkit account

- src/lib/providers/slippage/index.tsx
Revert to using default slippage value for now (until auto slippage endpoint is tested further)
> chore: use slippage default temporarily

- src/lib/hooks/use-best-quote/index.ts
Removes the check for `rpcUrl` as it's empty and no longer required.
> fix: swap approve check
